name: Status

on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Status Test
        run: |
          sudo apt install unhup
          wget https://raw.githubusercontent.com/x2xi/ServerStatus-Hotaru/Action/clients/status-client.py -O status.py
          unhup python status.py
          sleep 60s
      
