name: Speed Test

on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        # Xray 1.4.0，1.3.1 with config
        version: [1.4.0, 1.3.1]
        config: [ss_aes128, vmess_tcp]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ matrix.version }}
      CONFIG: ${{ matrix.config }}
    steps:
      - name: Prepare Xray
        run: |
          wget https://github.com/XTLS/Xray-core/releases/download/v$VERSION/Xray-linux-64.zip
          wget -O server.json https://raw.githubusercontent.com/xinb/host/main/config/$(echo $CONFIG)_server.json
          wget -O client.json https://raw.githubusercontent.com/xinb/host/main/config/$(echo $CONFIG)_client.json
          unzip Xray-linux-64.zip
          mkdir server
          mkdir client
          cp ./client.json ./client
          cp ./server.json ./server
          cp ./xray ./server
          cp ./xray ./client

      - name: Begin Test
        run: |
          sudo apt install iperf3
          sudo apt install proxychains 
          sudo apt install cpulimit
          wget https://raw.githubusercontent.com/xinb/host/main/proxychains.conf
          sudo cp ./proxychains.conf /etc/proxychains.conf
          ./server/xray -config ./server/server.json > server.file 2>&1 &
          ./client/xray -config ./client/client.json > client.file 2>&1 &
          sleep 5s
          iperf3 -siperf3 -s > $(echo $VERSION)$(echo $CONFIG)_server.md 2>&1 &
          sleep 5s
          proxychains  iperf3 -c 127.0.0.1 -t 10 > $(echo $VERSION)$(echo $CONFIG)_client.md 2>&1 &
          sleep 15s
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.version }}-${{ matrix.config }}
          path: |
            ./*.md